parameters:
#    everfail.example.class: Everfail\Bundle\Example

services:
#    everfail.example:
#        class: %everfail.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
